### PR TITLE
Re-adding  missing non-negativity check for measure. Not sure  why it was removed.

### PR DESCRIPTION
**Pull request by ravimad**

### CODE REVIEW

**Comment by samarion** [comment]
It's discharged through an Assertion injection in the lowering phase of the TerminationComponent

**Comment by ravimad** [comment]
I see. The positivity check didn't work on the examples I tried. So I re-added it in the termination phase.

**Comment by samarion** [comment]
It only gets checked during the verification phase.

**Comment by ravimad** [comment]
Looks like then it is needed in the termination check phase as well. Conceptually, its a part of checking measures.

**Comment by samarion** [comment]
Yes but termination checking is only valid if all verification checks pass as well...

**Comment by ravimad** [comment]
Yeah but checking contracts separately is a reasonable separation. But deferring a part of measures check to verification phase is tricky

**Pull request merged**
