### PR TITLE
Add cCode.noMangling annotation and split defines into header and C files

### PR DESCRIPTION
**Pull request by jad-hamza**

### CODE REVIEW

**Comment by vkuncak** [comment]
@jad-hamza : can we merge this?

**Comment by jad-hamza** [comment]
Yes I think so (if it works for the project)

**Comment by vkuncak** [comment]
See #1233 instead

**Comment by vkuncak** [comment]
Apparently merged through https://github.com/epfl-lara/stainless/pull/1233

**Pull request closed without merging**
