### PR TITLE
Induct flag only adds decreases check if type checker is enabled

### PR DESCRIPTION
**Pull request by Gorzen**

### CODE REVIEW

**Comment by jad-hamza** [comment]
> Can you please explain the rationale for this change? It seems to me that this commit does not actually change the behaviour of the test suite, is that right?
> 
> EDIT: By change I mean the second commit: [936f5f2](https://github.com/epfl-lara/stainless/commit/936f5f251232e66a5afb770b9a74756b39ffbedf)

The problem is that in the test suite, there are two contexts (one empty, and one with the correct options), and it looks like the empty context was used for the pipeline (and the type-checker option was off during `InductElimination`).

**Comment by romac** [comment]
@jad-hamza I see, thanks!

**Comment by Gorzen** [comment]
Fix #644

**Comment by romac** [comment]
@Gorzen Can you please check why the build failed?

**Comment by Gorzen** [comment]
> @Gorzen Can you please check why the build failed?

It's because of ParialCompiler and BodyEnsuring, check-models fails on them

**Comment by romac** [comment]
Blocked by#676

**Comment by Gorzen** [comment]
This may break caching in ComponentTestSuite, but as of right now options aren't passed properly to the extractor. (TypeCheckerEnabled) Which causes the tests to break as now we only add `decreases` if the type checker is enabled.

**Comment by romac** [comment]
Nice, thanks!

**Pull request merged**
