### PR TITLE
Add ScalaPrinter trait

### PR DESCRIPTION
**Pull request by jad-hamza**

### CODE REVIEW

**Comment by jad-hamza** [comment]
Fix part of https://github.com/epfl-lara/stainless/issues/751

Do you think the original printer should be used somewhere or can we just use `ScalaPrinter`? 

@saraswat For Real and BigInt, is this change ok for you?

**Comment by romac** [comment]
Here are a few more constructs which are currently not printed in a Scala-compatible way:

```scala
case NoTree(tpe) => p"(??? : $tpe)"

case Error(tpe, desc) =>
  p"""stainless.lang.error[$tpe]("$desc")"""

case Annotated(body, flags) if flags.nonEmpty =>
  p"($body):"
  for (f <- flags) p" @${f.asString(ctx.opts)} "

case Not(Equals(l, r)) => optP {
  p"$l != $r"
}

case IsConstructor(e, id) => p"$e.isInstanceOf[$id]"

case fs @ FiniteSet(rs, _) => p"{${rs}}"        // TODO
case fs @ FiniteBag(rs, _) => p"{${rs.toSeq}}"  // TODO
case fm @ FiniteMap(rs, dflt, _, _) =>          // TODO

case Not(ElementOfSet(e, s)) => p"$e \u2209 $s" // TODO
case ElementOfSet(e, s) => p"$e \u2208 $s"      // TODO
case SubsetOf(l, r) => p"$l \u2286 $r"          // TODO
case Not(SubsetOf(l, r)) => p"$l \u2288 $r"     // TODO
case SetAdd(s, e) => p"$s \u222A {$e}"          // TODO
case SetUnion(l, r) => p"$l \u222A $r"          // TODO
case BagUnion(l, r) => p"$l \u222A $r"          // TODO

case SetIntersection(l, r) => p"$l \u2229 $r"   // TODO
case BagIntersection(l, r) => p"$l \u2229 $r"   // TODO

case Not(expr) => p"\u00AC$expr"                // TODO
```

**Comment by jad-hamza** [comment]
Thanks! I added those as well.

- I'm not sure if I need to add some parentheses for operations such as `SetUnion`
- I removed `Map` for now, because `Map[A, B]` gets transformed to `Map[A, Option[B]]`

**Comment by vkuncak** [comment]
We may revisit this again later, but for now it looks like an improvement.

**Pull request merged**
