### PR TITLE
Bad line field accessor

### PR DESCRIPTION
**Pull request by jad-hamza**

### CODE REVIEW

**Comment by romac** [comment]
FYI the build got killed/stuck, so I just restarted it.

**Comment by romac** [comment]
@jad-hamza Does this fix #733?

**Comment by jad-hamza** [comment]
> @jad-hamza Does this fix #733?

Yes, but I'm not sure that's the correct way to do it?

**Comment by romac** [comment]
Looks good to me. I merged it manually.

**Pull request closed without merging**
