### PR TITLE
Move Rust interop generator from Inox

### PR DESCRIPTION
**Pull request by yannbolliger**
To make Inox completely frontend-independent, the tool that generates AST trees for Rust is moved to Stainless.
This is the dual of https://github.com/epfl-lara/inox/pull/155.

### CODE REVIEW

**Comment by samarion** [comment]
LGTM, but maybe @gsps should take a look?

**Comment by gsps** [comment]
Re https://github.com/epfl-lara/inox/pull/155#discussion_r634964616 :

> I hadn't realized this was going to live inside Inox. Is there any point having it here rather than in Stainless? I'd prefer if Inox stayed mostly frontend-independent (if possible).

Well, the original intention was to follow the structure of the existing serializer: implement all the Inox-related parts in Inox, and the additions needed to deal with Stainless trees in Stainless. That way we could generate the Rust-interop code for Inox alone as well.

That being said, this code is quite ad-hoc and doesn't actually separate things that cleanly, so I sympathize with the desire to localize it :-)

**Comment by vkuncak** [comment]
@samarion : can we merge this into the rust branch?

**Comment by samarion** [comment]
> @samarion : can we merge this into the rust branch?

You mean in Stainless? Yes, sure.

> Well, the original intention was to follow the structure of the existing serializer: implement all the Inox-related parts in Inox, and the additions needed to deal with Stainless trees in Stainless. That way we could generate the Rust-interop code for Inox alone as well.

I guess it could make sense to introduce Inox bindings for other languages, but maybe we could split them out into their own projects? I would expect the Rust bindings to also include some Rust code which allows idiomatic interaction with Inox.

**Comment by gsps** [comment]
Yes, that's a fair point. Currently both the hand-written and the auto-generated Rust parts live in [a crate that's part of rust-stainless](https://github.com/epfl-lara/rust-stainless/tree/master/stainless_data). For the time being, I'm happy to merge this PR and keep it all in Stainless for now.

**Pull request merged**
