### PR TITLE
Check match exhaustiveness in type-checker

### PR DESCRIPTION
**Pull request by romac**

### CODE REVIEW

**Comment by jad-hamza** [comment]
Isn't this covered by the translation `matchToIfThenElse` (when given `assumeExhaustive = false`)?

**Comment by romac** [comment]
Oh right, I didn't notice that.

In any case, I think that having a dedicated VC is a bit better for the user experience.

What do you think? Are there any downside to that?

**Comment by jad-hamza** [comment]
Yes I agree, the error reporting I wrote using exceptions everywhere is quite clumsy. I'm thinking maybe the current typing context should always hold an error message to know what to say when it fails.

If we add the separated exhaustiveness check, should we give `assumeExhaustive = true`?

**Comment by romac** [comment]
Oh, actually a VC was already emitted as a body assertion, but not always (ie. when the exhaustiveness check is trivial it seems).

But yeah I would keep as a dedicated VC, and pass `assumeExhaustive = true` to `matchToIfThenElse`. And perhaps, even type check the `MatchExpr` directly without translating it to an `if-then-else`?

**Comment by romac** [comment]
> I'm thinking maybe the current typing context should always hold an error message to know what to say when it fails.

Yes, that sounds like a good idea!

**Comment by jad-hamza** [comment]
> Oh, actually a VC was already emitted as a body assertion, but not always (ie. when the exhaustiveness check is trivial it seems).
> 
> But yeah I would keep as a dedicated VC, and pass `assumeExhaustive = true` to `matchToIfThenElse`. And perhaps, even type check the `MatchExpr` directly without translating it to an `if-then-else`?

Yes that's on the TODO list :) https://github.com/epfl-lara/stainless/issues/573

**Pull request merged**
