### PR TITLE
Recommend using Z3 4.8.6 instead of 4.7.1

### PR DESCRIPTION
**Pull request by jad-hamza**

### CODE REVIEW

**Comment by romac** [comment]
What's the rationale behind inlining the invariant? Is it only to work around the Z3 bug?

**Comment by jad-hamza** [comment]
Initially it was a workaround to the 4.8.7 bug yes, but since we're using 4.8.6 (nevermind the branch name :)) it shouldn't be needed. I thought I'd still leave this annotation so that the user can decide to inline or not (I guess this can speed up the verification in some cases).

**Comment by vkuncak** [comment]
Where is inlining actually taking place (which file and line)? I was curious but did not find it in the diff.

**Comment by jad-hamza** [comment]
It's in TypeChecker.scala when we see an ADT constructor (801 and 841)

**Comment by jad-hamza** [comment]
Can we merge this?

**Comment by vkuncak** [comment]
Yes. Can you do it, @jad-hamza ?

**Pull request merged**
