### PR TITLE
Reject usage of Scala's standard List

### PR DESCRIPTION
**Pull request by mantognini**
This PR follows from the discussion in #83. With it, this is now rejected:

```scala
//no import of stainless.collection.List
object NoStdList {
  // No usage of List[T]
  def bar0[T](l: List[T]) = {
    require(l.size > 0)
    l.head
  }

  // No usage of Nil
  def bar1 = Nil

  // No usage of ::
  def bar2 = 1 :: Nil

  // No usage of List.apply
  def bar3 = List(1, 2)
}
```

This patch is probably not rejecting all List usage but it should be a
first step in the right direction, especially to help user detect
missing import statements.

### CODE REVIEW

**Comment by romac** [comment]
👍 Sweet, been bitten by this too many times!

**Comment by samarion** [comment]
Looks good! Could you add some rejection tests for Stainless frontends and add the fix to dotty too, please?

**Comment by jad-hamza** [comment]
Thanks! In general is it possible to have a white list of things we accept, rather than a black list of things we reject?

**Comment by mantognini** [comment]
@samarion I'll have a look. IIRC we don't have a test suite to check something is rejected at the extraction.

@jad-hamza We kind of have it already, but the error message is not obvious: if the user uses something from the Scala library they will get a missing dependency from the Registry error. It's reported as an internal error, which is not really correct. Maybe this error message could be changed to be more understandable... I'll try something. :-)

**Comment by samarion** [comment]
@mantognini Indeed we don't have such a suite yet, but I believe it's high time we did. Many of @jad-hamza's issues would contribute examples to put in there.

**Comment by jad-hamza** [comment]
This PR doesn't affect the examples in https://github.com/epfl-lara/stainless/issues/103, I thought the `println` issue was related, as it doesn't belong to the "white list"?

**Comment by mantognini** [comment]
This PR is only dedicated to List & cie. I might work on a second PR for that later on. ;-)

**Pull request merged**
