### PR TITLE
Fix issue where local function calls in postcondition are wrongly transformed in imperative phase

### LINKED ISSUE #1159: ApplyLetRec arguments are not properly mapped in postconditions
The `inside` function is accepted by Stainless.

```scala
import stainless.lang._

object Test {

  def foo(): Unit = {
    var i = 0
    def isZero = i == 0

    def inside: Unit = {
      require(i <= 10)
      i += 1
    }.ensuring(_ =>
      isZero
    )

    inside
  }

}
```

The call `isZero` is transformed to `isZero(i)` where `i` refers to the initial value of `i` instead of the new value.

### PR DESCRIPTION
**Pull request by jad-hamza**
Fix #1159

### CODE REVIEW

**Comment by jad-hamza** [comment]
@samarion does this make sense? The problem was that in postconditions, `ImperativeCodeElimination` adds arguments to `ApplyLetRec` for which the proper mapping wasn't done.

**Comment by samarion** [comment]
This looks very iffy to me, I don't think applying the same substitution twice would be the right fix.

Could it be that the call to `toFunction` needs a different `State` argument? Maybe closer to the one used for `wrappedBody`? I'm unfortunately not very clear with the `ImperativeCodeElimination` transformation...

**Comment by vkuncak** [comment]
@mario-bucev : is this related to what was just merged?

**Comment by mario-bucev** [comment]
Yes, though the fix was not the same

**Pull request closed without merging**
