### PR TITLE
Enable strict arithmetic by default

### LINKED ISSUE #598: Enable --strict-arithmetic by default?

### PR DESCRIPTION
**Pull request by romac**
Close #598

### CODE REVIEW

**Comment by vkuncak** [comment]
Is there anything blocking this? Or maybe we introduce these errors as warnings and run them as default, whereas strict-arithmetic turns the warnings into errors?

**Comment by romac** [comment]
> Is there anything blocking this?

A lot of benchmarks are failing and I haven’t gotten around to fix them all yet.

> Or maybe we introduce these errors as warnings and run them as default, whereas strict-arithmetic turns the warnings into errors?

Yeah that is likely a sensible middle-ground, regardless of the status of the benchmarks. I’ll get on it and will fix the benchmarks all the same while I am at it, so that we don’t pollute the CI log with warnings anyway.

**Comment by romac** [comment]
For reference, here are the benchmarks that currently fail with strict arithmetic turned on: https://gist.github.com/romac/7eac6e7c474e0785e4fc305fcc3d52f0

**Comment by vkuncak** [comment]
I am reading these benchmarks and they seem fine with me. It's just that Int is a modular arithmetic. Given that we check e.g. negative indices and that, if things should be increasing, we should specify them, I am having second thoughts on whether we should fix the benchmarks. How about define a type alias 
```scala
type Int32 = Int
```
but then if you have something of this type then you do not report warnings on it? Ideally you would propagate a bit so you do emit warning on code such as
```scala
def f(x : Int32, y: Int) = x + y + 1
```

**Comment by romac** [comment]
As discussed today, we are just going to disable --strict-arithmetic for regular benchmarks, since we already have a StrictArithmetic test suite which exercises this feature.

**Comment by romac** [comment]
We still need a way for users to instruct Stainless that wrapping around is the expected behaviour for some expression, and thus opt-out of strict-arithmetic VC generation for this expression.

I suggest we go the Rust way and:

- Introduce such a `Wrapping` value class, with `+`, `-`, etc.
- Also provide an implicit value class with `wrapping_add`, `wrapping_sub`, etc.

and disable strict-arithmetic VC gen for calls to these methods.

What do you think?

**Comment by romac** [comment]
I think there is a better way of opting out of overflow checks, introduce an annotation `@wrapping` and a method

```scala
package stainless.math

@ignore
def wrapping[A](a: A): A = a
```

which is extracted as:

```scala
wrapping { body }

=>

@wrapping { body }
```

Then, we just disable overflow checks within any expression annotated with `@wrapping`.

**Comment by romac** [comment]
Note to self: Push documentation after merging.

**Comment by vkuncak** [comment]
@romac : This indeed sounds like a good plan: make strict-arithmetic default, introduce wrapping pseudo-function and @wrapping annotation for named methods. For benchmarks either change the options when invoking tests, or add the @wrapping once available.

**Pull request merged**
