### PR TITLE
WIP: Make lambdas total by default

### PR DESCRIPTION
**Pull request by romac**
Following the discussion in #92.

### CODE REVIEW

**Comment by jad-hamza** [comment]
Thanks for making that branch. [This example](https://gist.github.com/jad-hamza/f09dca5bf54d6d25cbf2160c8d7ec7ff) is still producing an invalid model, I can investigate later.

> [Warning ] - Model leads to runtime error: Reached empty tree in evaluation @46:3

**Comment by romac** [comment]
Yes there's still quite a few problem with those changes. And the [counting example](https://gist.github.com/romac/80ee13f9e4425098e236c7d31b4895f1) we wrote yesterday still yields an invalid counterexample, but with the `require(false)` now at least.

**Comment by jad-hamza** [comment]
Yes the gist is the Counting example, but a bit simplified.

**Comment by romac** [comment]
See https://gist.github.com/romac/7d8ee52865dbd41e66e34164c0c102c4

**Comment by jad-hamza** [comment]
Have you tried the one I linked? It could be due to non-determinism in the solver

**Comment by romac** [comment]
Yes that's the one I posted the log of above. Yeah it could be that or that we don't have the same Z3 version.

**Comment by jad-hamza** [comment]
I updated https://gist.github.com/jad-hamza/f09dca5bf54d6d25cbf2160c8d7ec7ff with some evaluation debug (that leads to the empty tree being evaluated).

**Comment by jad-hamza** [comment]
Here's the debug output with information from the Inox evaluator as well: https://gist.github.com/jad-hamza/a87ef04d594ff6d578c2ce074e424d9c

**Comment by romac** [comment]
This is really weird, especially since I can’t reproduce it. Can you please print the full Stainless and Inox programs as well? How about the original Counting example? Do your run into the same error there?

**Comment by jad-hamza** [comment]
Can you try with --functions=theorem? Without it I cannot reproduce the bug. 
These are the options I'm using `--functions=theorem --vc-cache --debug=verification --check-models`. I'm also able to reproduce on the original version.

This is the full Stainless program: https://gist.github.com/jad-hamza/830e07aad73d0ca206d6295f7fe0c365

**Comment by romac** [comment]
Alright, so it seems the culprit is indeed `--functions=theorem`, I get the same error with it.

It seems that, for some reason that I am currently unable to figure from reading the source, when this option is active `processMsg`'s body is replaced by an empty tree, as evidenced by [this line](https://gist.github.com/jad-hamza/830e07aad73d0ca206d6295f7fe0c365#file-fullprogram-scala-L174).

```scala
def processMsg(thiss: Behavior, msg: Msg, ctx: ActorContext): Behavior = <empty tree>[Behavior]
```

**Comment by jad-hamza** [comment]
Thanks. I opened an issue https://github.com/epfl-lara/stainless/issues/112, because the behavior also appear in the master branch.

**Comment by romac** [comment]
Copy-paste of @jad-hamza's comment on my fork:

> I had some pending changes, It should be OK now for total functions. I put some regression tests on hold for the moment. We should probably discuss with the others on how to implement support for lambdas with preconditions, we already discussed various options.

> To be safe we should also prevent extraction of requires inside lambdas for the moment, until the next pull request that adds higher order contracts.

**Comment by jad-hamza** [comment]
I have made lots of changes in files that I'm not familiar with. Does that look good for total functions?

**Comment by jad-hamza** [comment]
I'm leaving this as is for the moment (anyone welcome to continue one of the approaches we discussed :)). This branch should work ok if you don't use the require keyword for anonymous lambdas

**Comment by mantognini** [comment]
Superseded by #160.

**Pull request closed without merging**
