### PR TITLE
Extract `set.isEmpty` as `set == Set()`

### PR DESCRIPTION
**Pull request by romac**

### CODE REVIEW

**Comment by samarion** [comment]
Please fix in the dotty extractor as well.

**Comment by romac** [comment]
Done.

**Comment by romac** [comment]
#126 kicked in again (and once again it is`NNFSimple` which fails to verify, haven't been able to reproduce it).

**Comment by mantognini** [comment]
Merged in ddff4c982c7455ec5fc1af87cd4120ef8c046a02.

**Pull request closed without merging**
