### PR TITLE
Add more support for bitvector operations and documentation

### PR DESCRIPTION
**Pull request by jad-hamza**
For issues #950, #954, #961

### CODE REVIEW

**Comment by jad-hamza** [comment]
I also added some documentation to address https://github.com/epfl-lara/stainless/issues/948

**Comment by vkuncak** [comment]
@jad-hamza : For documentation, we can think of all these types as finite intervals of mathematical integers. Could you describe the conversion functions from this point of view? This would explain the general cases and would complement the examples that you gave so far.

**Comment by jad-hamza** [comment]
Yes good idea, I've added some explanations. I hope I didn't make mistakes, could someone double check? I'll have a fresh look tomorrow as well.

**Comment by deiruch** [comment]
Very helpful! LGTM

**Pull request merged**
