### PR TITLE
Recommend using Z3 4.8.5 instead of 4.7.1

### PR DESCRIPTION
**Pull request by jad-hamza**

### CODE REVIEW

**Comment by romac** [comment]
Are we sure that this is a good idea, given that ScalaZ3 tests fail with both Z3 4.8.4 and Z3 4.8.5?

**Comment by jad-hamza** [comment]
The tests on Inox and Stainless are working (locally) with the command-line version of Z3 4.8.5 (smt-z3). I haven't tried the bolts examples though. In my proofs I'm using Z3 4.8.5 (because of this bug on 4.7.1 https://github.com/epfl-lara/stainless/issues/497), and it's working ok so far. However I agree that we can postpone this pull request until we figure out what's going on with ScalaZ3, and do some more tests with Z3 4.8.5 (namely bolts, and changing the Z3 bin that larabot has access to).

**Comment by vkuncak** [comment]
A bug in a solver is also our bug :(
We should move away from versions for which we actually managed to trigger a bug as fast as possible.

**Comment by romac** [comment]
Alright! I am going to upgrade Z3 to 4.8.5 on larabot and trigger a new build to make sure everything is working correctly, and then I will merge this pull request.

**Comment by vkuncak** [comment]
Ok, but be prepared for failures. I was just doing this on laraquad3 and the build failed.

**Comment by romac** [comment]
@vkuncak Did you get the same errors? http://laraquad4.epfl.ch:9000/epfl-lara/stainless/build/3939/23284

**Comment by romac** [comment]
Weirdly enough, this test suite goes fine on my machine with Z3 4.8.5.

**Comment by romac** [comment]
On the other hand, running

`stainless-scalac  --solvers=smt-z3 --type-checker ../benchmarks/typechecker/valid/List.scala`

yields

```
[info] [ Fatal  ] Run has failed with error: inox.package$FatalError: Missfomed SMT source in (lambda ((x!3 T!243)) (= x!3 (T!244 6))):
[info] [ Fatal  ] Unknown SMT term
[info] [ Fatal  ]
[info] [ Fatal  ] inox.Reporter.onFatal(Reporter.scala:39)
[info] [ Fatal  ] inox.Reporter.internalError(Reporter.scala:57)
[info] [ Fatal  ] inox.Reporter.internalError(Reporter.scala:100)
[info] [ Fatal  ] inox.Reporter.internalError(Reporter.scala:103)
[info] [ Fatal  ] stainless.verification.VerificationChecker.checkVC(VerificationChecker.scala:264)
[info] [ Fatal  ] stainless.verification.VerificationChecker.checkVC$(VerificationChecker.scala:202)
[info] [ Fatal  ] stainless.verification.VerificationChecker$Checker$1.checkVC(VerificationChecker.scala:303)
[info] [ Fatal  ] stainless.verification.VerificationChecker.$anonfun$checkVCs$3(VerificationChecker.scala:100)
```

cc @jad-hamza

**Comment by romac** [comment]
Reverting to Z3 4.7.1 on laraquad until we figure this out.

**Comment by vkuncak** [comment]
I have finished a single-threaded run of `sbt it:test` on laraquad3 and all tests passed.

**Comment by vkuncak** [comment]
Also `sbt test` passes.

**Comment by vkuncak** [comment]
@jad-hamza can you check why verifying `benchmarks/typechecker/valid/List.scala` with type checker fails on z3-4.8.5 ?

**Comment by vkuncak** [comment]
Actually, for this benchmark, why does it not work with cvc4?
It gets unknown in some `groupBy` VCs. It looks like issue is in the use of `Map` that are not supported in the same way in CVC4 and Z3, and there were some changes to how they are handled in Z3 recently.
Maybe remove Maps from the benchmark for now and make an issue to fix them.
```bash
./stainless-dotty --solvers=smt-cvc4 --type-checker frontends/benchmarks/typechecker/valid/List.scala  --functions=groupBy

[ Error  ] {* -> dlft$20}@?:? (of class inox.ast.Expressions$FiniteMap) is unsupported by solver smt-cvc4:
[ Error  ]   Cannot encode map with non-constant default value
[ Error  ] {* -> dlft$19}@?:? (of class inox.ast.Expressions$FiniteMap) is unsupported by solver smt-cvc4:
[ Error  ]   Cannot encode map with non-constant default value
[ Error  ] {* -> dlft$16}@?:? (of class inox.ast.Expressions$FiniteMap) is unsupported by solver smt-cvc4:
[ Error  ]   Cannot encode map with non-constant default value
[  Info  ]  - Result for 'cast correctness' VC for groupBy @583:56:
[Warning ]  => UNKNOWN
[  Info  ]  - Result for 'cast correctness' VC for groupBy @583:56:
[Warning ]  => UNKNOWN
[  Info  ]  - Result for 'cast correctness' VC for groupBy @583:56:
[Warning ]  => UNKNOWN
[ Error  ] {* -> dlft$23}@?:? (of class inox.ast.Expressions$FiniteMap) is unsupported by solver smt-cvc4:
[ Error  ]   Cannot encode map with non-constant default value
[  Info  ]  - Result for 'map usage' VC for groupBy @583:56:
[Warning ]  => UNKNOWN
[  Info  ]   ┌───────────────────┐
[  Info  ] ╔═╡ stainless summary ╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
[  Info  ] ║ └───────────────────┘                                                                                                                        ║
[  Info  ] ║ groupBy  non-negative measure                  valid from cache              frontends/benchmarks/typechecker/valid/List.scala:7:23    0.196 ║
[  Info  ] ║ groupBy  body assertion: match exhaustiveness  valid from cache              frontends/benchmarks/typechecker/valid/List.scala:578:5   0.195 ║
[  Info  ] ║ groupBy  measure decreases                     valid from cache              frontends/benchmarks/typechecker/valid/List.scala:582:38  0.195 ║
[  Info  ] ║ groupBy  cast correctness                      unknown           U:smt-cvc4  frontends/benchmarks/typechecker/valid/List.scala:583:56  0.463 ║
[  Info  ] ║ groupBy  cast correctness                      unknown           U:smt-cvc4  frontends/benchmarks/typechecker/valid/List.scala:583:56  0.463 ║
[  Info  ] ║ groupBy  cast correctness                      unknown           U:smt-cvc4  frontends/benchmarks/typechecker/valid/List.scala:583:56  0.465 ║
[  Info  ] ║ groupBy  map usage                             unknown           U:smt-cvc4  frontends/benchmarks/typechecker/valid/List.scala:583:56  0.465 ║
[  Info  ] ╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢                                                                              
[  Info  ] ║ total: 7    valid: 3    (3 from cache) invalid: 0    unknown: 4    time:   2.442                                                             ║
[  Info  ] ╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝  
```

**Comment by jad-hamza** [comment]
> @jad-hamza can you check why verifying `benchmarks/typechecker/valid/List.scala` with type checker fails on z3-4.8.5 ?

I was able to reproduce this on my machine so I'll try to debug it. It looks like the tests ignore these internal errors and keep on going?

> Actually, for this benchmark, why does it not work with cvc4?

Same as these other benchmarks probably: https://github.com/epfl-lara/stainless/blob/0c98faa267bfcf15a36d2e891c45ccfa7c881987/frontends/scalac/src/it/scala/stainless/verification/VerificationSuite.scala#L106

>  Maybe remove Maps from the benchmark for now and make an issue to fix them.

Shouldn't we keep it if it works with Z3?

**Comment by jad-hamza** [comment]
> @jad-hamza can you check why verifying `benchmarks/typechecker/valid/List.scala` with type checker fails on z3-4.8.5 ?

I found where the issue comes from: https://github.com/epfl-lara/inox/issues/104

**Comment by jad-hamza** [comment]
Even with epfl-lara/inox#104 fixed, the `List` benchmark still fails due to an issue in Z3: https://github.com/Z3Prover/z3/issues/2409

**Comment by vkuncak** [comment]
We should explore deemphasizing the use of z3 specific features including
its magical arrays.

**Comment by jad-hamza** [comment]
The Z3 issue has been fixed! (thanks @NikolajBjorner)

Stainless tests should now go through with this version of Inox https://github.com/epfl-lara/inox/pull/105 and Z3 master.

**Comment by romac** [comment]
LGTM

**Comment by jad-hamza** [comment]
Perhaps we wait before merging this, since the tests do not go through at the moment (waiting for https://github.com/epfl-lara/inox/pull/105 and new Z3 release for https://github.com/Z3Prover/z3/issues/2409)

**Comment by romac** [comment]
Closing in favor of #714

**Pull request closed without merging**
