### PR TITLE
Add support for GenC @export annotation on types

### PR DESCRIPTION
**Pull request by jad-hamza**
Fix https://github.com/epfl-lara/stainless/issues/1007

@deiruch Should we also prevent name mangling for `val`'s and `var`'s of `@export`'ed classes?

### CODE REVIEW

**Comment by deiruch** [comment]
> @deiruch Should we also prevent name mangling for `val`'s and `var`'s of `@export`'ed classes?

I don't think it's scrictly necessary right now, but it'd be consistent and will give us more options for the future.

**Comment by jad-hamza** [comment]
Should be good now, but it has not been tested extensively :)
Please tell me if there's something wrong!

**Comment by deiruch** [comment]
It works *almost* as it should! :)

It seems that all functions in an annotated type get exported - even including `inv()`. I think it should still only export explicitly annotated functions.

**Comment by jad-hamza** [comment]
Hmm I thought I disabled the propagation of `@export`. Are you sure all functions get exported, or is it only the special function `inv`?

**Comment by deiruch** [comment]
Sorry, you're absolutely right. It's just `inv`.

**Comment by jad-hamza** [comment]
Thanks for the report! Fixed in https://github.com/epfl-lara/stainless/pull/1019

**Pull request merged**
