### PR TITLE
Upgrade Dotty to 0.12.0-RC1

### PR DESCRIPTION
**Pull request by romac**
## Supported

- [x] Extension Methods
- [x] Refinement types in functions parameters
- [x] Refinement types in constructor parameters
- [x] Erased Terms as ghost terms (partially working, still need to propagate annotations)
- [x] Opaque Types (they get dealiased during extraction, better support in #470)
- [x] Dependent Function Types (#470)

## Untested

- ADTs
- Enumerations
- Intersection Types
- Union Types
- Type Lambdas
- Match Types
- Typeclass Derivation
- Multiversal Equality
- Trait Parameters
- Inlining by Rewriting
- Meta Programming
- By-Name Implicits
- Auto Parameter Tupling
- Named Type Arguments

## Untested (coming in 0.13)

- Witnesses
- Top-level definitions

## Unsupported

- Kind Polymorphism
- TASTy Reflect

### CODE REVIEW

**Comment by romac** [comment]
Sneak peek at the WIP refinement types integration:

### Input:
screenshot 2019-01-25 17 46 03

### Output:
screenshot 2019-01-25 17 46 15

/cc @gsps @vkuncak @samarion @jad-hamza

**Comment by vkuncak** [comment]
This is very, very cool, @romac !

**Comment by jad-hamza** [comment]
Nice!

**Comment by romac** [comment]
Somehow, the DottyExtraction suite fails when type-checking with errors such as `expected A, found A`, whereas feeding `stainless-dotty/run` all the files in eg. `verification/valid` succeeds.

**Comment by vkuncak** [comment]
Is it not again the issue that stainless does not run all phases of the compiler by default?

**Comment by romac** [comment]
I don’t think so. Both the test suite and the regular way of invoking stainless should run the same compiler phases. Might be a big due to building one single symbol table for all benchmarks, or something like that. Will continue to investigate further.

**Comment by samarion** [comment]
I pushed https://github.com/epfl-lara/stainless/commit/1c89a595de7abbed43aa315226ac67a7085ddb21 to https://github.com/epfl-lara/stainless/commit/cd5518ed73edeca93f87f0cdea0fb795d6263f6b which re-enables the dotty frontend.

However, support for pi- and refinement-types, as well as type members is still not complete so we can leave this PR open until those features have been implemented.

**Comment by romac** [comment]
Thanks for fixing the plugin :) I will get on the rest!

**Comment by romac** [comment]
Π-types (dependent functions types) are now supported in #470, and I opened an issue (#477) to track the remaining work (ie. extract types by traversing type trees recursively).

**Pull request merged**
